### ISSUE TITLE
Same color for same courses?

### ISSUE THREAD

**Issue by Hmmmmmmmmmm** [Surine/ScheduleX#9]
Love the idea of changing color pattern!
But am having problems with identify same courses, try match the courses with same name/place to same color?

**Comment by Surine** [comment]
Thanks for your advice, I'm also aware of this problem, because the id of each course is different, the color is also different. I didn't get a good idea before your reply. now, maybe I can create a HashMap with the course name as the key and color as the value,and then courses with the same name will have the same color.

Thank you again!
